CREATE DATABASE ESTACIO

CREATE TABLE ALUNO (
  ID int PRIMARY KEY,
  NOME varchar(20) NOT NULL,
  CURSO int NOT NULL,
);

CREATE TABLE CURSO (
  ID int PRIMARY KEY,
  NOME varchar(20) NOT NULL,
);

INSERT INTO ALUNO (ID,NOME,CURSO)
VALUES (1,'JOAO',2)
VALUES (2,'MARIA',2)
VALUES (3,'PEDRO',1)

VALUES (4,'ANA',4)
VALUES (5,'TIAGO',NULL)

INSERT INTO CURSO (ID,NOME)
VALUES (1,'JAVA')
VALUES (2,'C++')
VALUES (3,'C#')
VALUES (4,'PHP')